package hr.fet.iDom.model.VO;

import hr.fet.iDom.model.VO.common.EditRoomVO;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.common.RowSetIteratorHelper;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 14 11:22:51 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EditRoomVOImpl extends ViewObjectImpl implements EditRoomVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EditRoomVOImpl() {
    }

    /**
     * Returns the bind variable value for RoomId.
     * @return bind variable value for RoomId
     */
    public String getRoomId() {
        return (String)getNamedWhereClauseParam("RoomId");
    }

    /**
     * Sets <code>value</code> for bind variable RoomId.
     * @param value value to bind as RoomId
     */
    public void setRoomId(String value) {
        setNamedWhereClauseParam("RoomId", value);
    }
    
    private void revertChanges(Row currRow){
        if (currRow != null){
            currRow.refresh(Row.REFRESH_UNDO_CHANGES | Row.REFRESH_WITH_DB_FORGET_CHANGES);
        }
    }
    
    public void partialRollBack(){
        ViewObject vo = this;
        RowSetIterator iter = vo.createRowSetIterator(null);
        while (iter.hasNext()){
            Row nextRow = iter.next();
            revertChanges(nextRow);
            
        }
        this.executeQuery();
    }
}
