package hr.fet.iDom.model.VO.client;

import hr.fet.iDom.model.VO.common.EditRoomVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 14 11:29:00 CEST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EditRoomVOClient extends ViewUsageImpl implements EditRoomVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EditRoomVOClient() {
    }

    public void partialRollBack() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"partialRollBack",null,null);
        return;
    }
}
