package hr.fet.iDom.model.VO.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 14 11:29:00 CEST 2015
// ---------------------------------------------------------------------
public interface EditRoomVO extends ViewObject {
    void partialRollBack();
}
